export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    SET_LOGGEDIN_USER:"SET_LOGGEDIN_USER",
    SET_LOGIN_USER:"SET_LOGIN_USER",
    SET_USER_LOGOUT:"SET_USER_LOGOUT",
    SET_CART_PRODUCTS:"SET_CART_PRODUCTS",
    REMOVE_CART_PRODUCTS:"REMOVE_CART_PRODUCTS",
    SET_ORDER_HISTORY_LIST:"SET_ORDER_HISTORY_LIST",
    REMOVE_ORDER_HISTROY_PRODUCTS:"REMOVE_ORDER_HISTROY_PRODUCTS"
}

